[workspace]
members = [
  "pinyin",
  "pinyin_svc",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units=1
#debug = 1

[profile.dev]
split-debuginfo = "unpacked"
